#pragma checksum "C:\Users\COMPUCLUB\Documents\My files\AppFinal\AppFinal\AppFinal\Home.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "69586E381E9E7C927EDC8E44D5AC3618"
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18033
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Phone.Controls;
using Microsoft.Phone.Controls.Maps;
using System;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Automation.Peers;
using System.Windows.Automation.Provider;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Imaging;
using System.Windows.Resources;
using System.Windows.Shapes;
using System.Windows.Threading;


namespace AppFinal {
    
    
    public partial class PanoramaPage1 : Microsoft.Phone.Controls.PhoneApplicationPage {
        
        internal System.Windows.Controls.Grid LayoutRoot;
        
        internal Microsoft.Phone.Controls.Maps.Map MapaUn;
        
        internal System.Windows.Shapes.Ellipse America_Sur;
        
        internal System.Windows.Shapes.Ellipse America_Norte;
        
        internal System.Windows.Controls.StackPanel Search;
        
        internal System.Windows.Controls.TextBox Input_Bus;
        
        internal System.Windows.Controls.Button Busqueda_sitio;
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Windows.Application.LoadComponent(this, new System.Uri("/AppFinal;component/Home.xaml", System.UriKind.Relative));
            this.LayoutRoot = ((System.Windows.Controls.Grid)(this.FindName("LayoutRoot")));
            this.MapaUn = ((Microsoft.Phone.Controls.Maps.Map)(this.FindName("MapaUn")));
            this.America_Sur = ((System.Windows.Shapes.Ellipse)(this.FindName("America_Sur")));
            this.America_Norte = ((System.Windows.Shapes.Ellipse)(this.FindName("America_Norte")));
            this.Search = ((System.Windows.Controls.StackPanel)(this.FindName("Search")));
            this.Input_Bus = ((System.Windows.Controls.TextBox)(this.FindName("Input_Bus")));
            this.Busqueda_sitio = ((System.Windows.Controls.Button)(this.FindName("Busqueda_sitio")));
        }
    }
}

